version: '3'

services:

  apache:
    image: sample/apache
    container_name: sample-apache
    build:
      context: "./apache"
      dockerfile: "Dockerfile"
    ports:
     - "80:80"
     - "443:443"
    restart: always
    volumes:
     - ./apache/conf.d:/etc/apache2/conf.d
     - ./apache/ssl:/etc/apache2/ssl
     - ./apache/logs:/var/log/apache2
     - ../htdocs:/var/www/html
